<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <PlatformTarget>x64</PlatformTarget>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <BuildNumber>0</BuildNumber>
  </PropertyGroup>

  <!-- DEBUG CONFIGURATION -->
  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <Optimize>false</Optimize>
    <SelfContained>false</SelfContained>
    <PublishSingleFile>false</PublishSingleFile>
    <PublishTrimmed>false</PublishTrimmed>
    <IncludeNativeLibrariesForSelfExtract>false</IncludeNativeLibrariesForSelfExtract>
    <PublishReadyToRun>false</PublishReadyToRun>
  </PropertyGroup>

  <!-- RELEASE CONFIGURATION -->
  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <Optimize>true</Optimize>
    <EnableAVX2>true</EnableAVX2>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <PublishReadyToRun>true</PublishReadyToRun>
  </PropertyGroup>

  <PropertyGroup>
    <Version>1.0.0</Version>
    <InformationalVersion>$(Version).$(BuildNumber)+$(SourceRevisionId)</InformationalVersion>
    <AssemblyVersion>$(Version)</AssemblyVersion>
    <FileVersion>$(Version).$(BuildNumber)</FileVersion>
  </PropertyGroup>

    <Target Name="RemoveUnwantedFiles" AfterTargets="Publish" Condition="'$(Configuration)' == 'Release'">
    <ItemGroup>
      <FilesToDelete Include="$(PublishDir)**\*.pdb" />
      <FilesToDelete Include="$(PublishDir)**\*.lib" />
    </ItemGroup>

    <Delete Files="@(FilesToDelete)" />
  </Target>


  <ItemGroup>

    <Content Include="models/*.*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="FFmpeg.AutoGen" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime.DirectML" />
    <PackageReference Include="Onnxify" />
    <PackageReference Include="OpenCvSharp4" />
    <PackageReference Include="OpenCvSharp4.runtime.win" />
    <PackageReference Include="Spectre.Console" />
    <PackageReference Include="UltraFaceDotNet" />
  </ItemGroup>

</Project>
